# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gally', '0004_auto_20191011_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
